# Generated by Django 5.1.1 on 2025-02-17 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField()),
                ('description', models.TextField()),
                ('participant_limit', models.IntegerField()),
                ('poster', models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
