# Generated by Django 5.1.1 on 2025-02-18 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='participants', to='users.event'),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='event_posters/'),
        ),
    ]
