# Generated by Django 5.1.1 on 2025-02-18 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_events_event_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='events',
        ),
        migrations.AddField(
            model_name='customuser',
            name='events',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.event'),
        ),
    ]
