# Generated by Django 5.1.1 on 2025-02-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_event_created_by_remove_customuser_events_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='events',
        ),
        migrations.AddField(
            model_name='customuser',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='participants', to='users.event'),
        ),
    ]
