# Generated by Django 5.1.1 on 2025-02-18 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_customuser_events_customuser_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='participant_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
